GLOBALS = globals()
PRODUCT_NAME = 'qPloneCaptchas'
CAPTCHAS_COUNT = 165
LAYERS = ['captchas', 'plone_captchas']
LAYER_QCOMMENTS = 'captchas_qcomments'
LAYER_DISCUSSION = 'captchas_discussion'
LAYER_FORMMAILER = 'captchas_ploneformmailer'
ALL_LAYERS = LAYERS + [LAYER_QCOMMENTS, LAYER_DISCUSSION, LAYER_FORMMAILER]
TOOL_ICON = 'tool.gif'
TOOL_ID = 'portal_captchas'
havePIL = True
